# Generated by Django 6.0.7 on 2026-07-07 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('barcode', models.CharField(blank=True, default='', max_length=100, verbose_name='بارکد')),
                ('qr_code', models.CharField(blank=True, default='', max_length=200, verbose_name='QR Code')),
                ('category', models.CharField(blank=True, default='', max_length=100, verbose_name='دسته\u200cبندی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='تصویر')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('sale_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قیمت فروش')),
                ('wholesale_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قیمت عمده')),
                ('retail_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قیمت جزئی')),
                ('dealer_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قیمت نمایندگی')),
                ('export_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قیمت صادراتی')),
                ('special_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قیمت ویژه')),
                ('profit_percent', models.DecimalField(decimal_places=2, default=30, max_digits=5, verbose_name='درصد سود')),
                ('fixed_profit', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='سود ثابت (ریال)')),
                ('cost_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قیمت تمام\u200cشده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='مقدار مصرف')),
                ('unit', models.CharField(default='kg', max_length=10, verbose_name='واحد')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_materials', to='materials.material', verbose_name='ماده اولیه')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'ماده مصرفی محصول (BOM)',
                'verbose_name_plural': 'لیست مواد مصرفی محصولات (BOM)',
                'unique_together': {('product', 'material')},
            },
        ),
    ]
