# Generated by Django 6.0.7 on 2026-07-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('production_date', models.DateField(verbose_name='تاریخ تولید')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت\u200cها')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('completed', 'تکمیل شده')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تولید روزانه',
                'verbose_name_plural': 'تولیدات روزانه',
                'ordering': ['-production_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='مقدار برنامه\u200cریزی شده')),
                ('actual_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True, verbose_name='مقدار واقعی')),
                ('unit_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='هزینه هر واحد')),
                ('total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='هزینه کل')),
            ],
            options={
                'verbose_name': 'ماده مصرفی سفارش',
                'verbose_name_plural': 'مواد مصرفی سفارشات',
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='تعداد')),
                ('unit_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='هزینه هر واحد')),
                ('total_cost', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='هزینه کل')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('in_progress', 'در حال تولید'), ('completed', 'تکمیل شده'), ('cancelled', 'لغو شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='اولویت')),
                ('planned_date', models.DateField(verbose_name='تاریخ برنامه\u200cریزی')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'سفارش تولید',
                'verbose_name_plural': 'سفارشات تولید',
                'ordering': ['-created_at'],
            },
        ),
    ]
