# Generated by Django 6.0.7 on 2026-07-07 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0002_initial'),
        ('production', '0001_initial'),
        ('products', '0001_initial'),
        ('workers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyproduction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_productions', to='products.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='dailyproduction',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='daily_productions', to='workers.worker', verbose_name='کارگر'),
        ),
        migrations.AddField(
            model_name='productionmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='materials.material', verbose_name='ماده اولیه'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده'),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='products.product', verbose_name='محصول'),
        ),
        migrations.AddField(
            model_name='productionmaterial',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='production.productionorder', verbose_name='سفارش تولید'),
        ),
    ]
