# Generated by Django 6.0.7 on 2026-07-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('company', models.CharField(blank=True, default='', max_length=200, verbose_name='شرکت')),
                ('phone', models.CharField(blank=True, default='', max_length=15, verbose_name='تلفن')),
                ('email', models.EmailField(blank=True, default='', max_length=254, verbose_name='ایمیل')),
                ('address', models.TextField(blank=True, default='', verbose_name='آدرس')),
                ('city', models.CharField(blank=True, default='', max_length=100, verbose_name='شهر')),
                ('tax_number', models.CharField(blank=True, default='', max_length=20, verbose_name='شماره مالیاتی')),
                ('national_id', models.CharField(blank=True, default='', max_length=10, verbose_name='کد ملی')),
                ('balance', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مانده حساب')),
                ('credit_limit', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حد اعتبار')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['name'],
            },
        ),
    ]
