# Generated by Django 6.0.7 on 2026-07-07 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت قبلی')),
                ('new_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت جدید')),
                ('change_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, default='', verbose_name='دلیل تغییر')),
            ],
            options={
                'verbose_name': 'تاریخچه قیمت ماده',
                'verbose_name_plural': 'تاریخچه قیمت مواد',
                'ordering': ['-change_date'],
            },
        ),
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='materials.materialcategory', verbose_name='دسته والد')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی مواد اولیه',
                'verbose_name_plural': 'دسته\u200cبندی مواد اولیه',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('unit', models.CharField(choices=[('kg', 'کیلوگرم'), ('piece', 'عدد'), ('unit', 'واحد'), ('meter', 'متر'), ('liter', 'لیتر'), ('roll', 'گرم')], default='kg', max_length=10, verbose_name='واحد')),
                ('purchase_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قیمت خرید')),
                ('purchase_date', models.DateField(blank=True, null=True, verbose_name='تاریخ خرید')),
                ('supplier', models.CharField(blank=True, default='', max_length=200, verbose_name='تامین\u200cکننده')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='کد')),
                ('barcode', models.CharField(blank=True, default='', max_length=100, verbose_name='بارکد')),
                ('qr_code', models.CharField(blank=True, default='', max_length=200, verbose_name='QR Code')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='حداقل موجودی')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='موجودی فعلی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='materials/', verbose_name='تصویر')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='materials.materialcategory', verbose_name='دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'ماده اولیه',
                'verbose_name_plural': 'مواد اولیه',
                'ordering': ['name'],
            },
        ),
    ]
