# Generated by Django 6.0.7 on 2026-07-07 23:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('materials', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='materialpricehistory',
            name='changed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='تغییردهنده'),
        ),
        migrations.AddField(
            model_name='materialpricehistory',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='materials.material', verbose_name='ماده اولیه'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['code'], name='materials_m_code_2c19b2_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['name'], name='materials_m_name_f87747_idx'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['category'], name='materials_m_categor_58e1ac_idx'),
        ),
    ]
