# Generated by Django 6.0.7 on 2026-07-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='شماره فاکتور')),
                ('type', models.CharField(choices=[('sale', 'فروش'), ('return', 'برگشت'), ('proforma', 'پیش\u200cفاکتور')], default='sale', max_length=10, verbose_name='نوع')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('sent', 'ارسال شده'), ('paid', 'پرداخت شده'), ('partial', 'پرداخت جزئی'), ('cancelled', 'لغو شده')], default='draft', max_length=10, verbose_name='وضعیت')),
                ('issue_date', models.DateField(verbose_name='تاریخ صدور')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='جمع کل')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ تخفیف')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ مالیات')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ کل')),
                ('paid_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ پرداختی')),
                ('remaining_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ باقیمانده')),
                ('payment_method', models.CharField(blank=True, default='', max_length=50, verbose_name='روش پرداخت')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'فاکتور',
                'verbose_name_plural': 'فاکتورها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300, verbose_name='توضیحات')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='تعداد')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت هر واحد')),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد تخفیف')),
                ('tax_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد مالیات')),
                ('total', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='جمع')),
            ],
            options={
                'verbose_name': 'قلم فاکتور',
                'verbose_name_plural': 'اقلام فاکتور',
            },
        ),
    ]
