# Generated by Django 5.2.16 on 2026-07-09 14:37

import django_jalali.db.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=django_jalali.db.models.jDateField(blank=True, null=True, verbose_name='تاریخ سررسید'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=django_jalali.db.models.jDateField(verbose_name='تاریخ صدور'),
        ),
    ]
