# Generated by Django 5.2.16 on 2026-07-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_alter_invoice_due_date_alter_invoice_issue_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='due_date',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(verbose_name='تاریخ صدور'),
        ),
    ]
