# Generated by Django 5.2.16 on 2026-07-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_remove_invoice_due_date_alter_invoice_issue_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='type',
            field=models.CharField(choices=[('sale', 'فاکتور فروش'), ('return', 'برگشت از فروش'), ('proforma', 'پیش\u200cفاکتور'), ('official', 'فاکتور رسمی'), ('credit', 'اعتباری'), ('cash', 'نقدی')], default='sale', max_length=10, verbose_name='نوع'),
        ),
    ]
