# Generated by Django 6.0.7 on 2026-07-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام هزینه')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='مبلغ (ریال)')),
                ('category', models.CharField(blank=True, default='', max_length=50, verbose_name='دسته\u200cبندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'هزینه ثابت',
                'verbose_name_plural': 'هزینه\u200cهای ثابت',
                'ordering': ['name'],
            },
        ),
    ]
