# Generated by Django 6.0.7 on 2026-07-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('message', models.TextField(verbose_name='پیام')),
                ('type', models.CharField(choices=[('info', 'اطلاعات'), ('warning', 'هشدار'), ('error', 'خطا')], default='info', max_length=10, verbose_name='نوع')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده')),
                ('reference_type', models.CharField(blank=True, default='', max_length=50, verbose_name='نوع مرجع')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه مرجع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'اعلان',
                'verbose_name_plural': 'اعلانات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True, verbose_name='کلید')),
                ('value', models.TextField(blank=True, default='', verbose_name='مقدار')),
                ('category', models.CharField(choices=[('general', 'عمومی'), ('financial', 'مالی'), ('inventory', 'انبار'), ('production', 'تولید')], default='general', max_length=20, verbose_name='دسته\u200cبندی')),
                ('description', models.TextField(blank=True, default='', verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیم',
                'verbose_name_plural': 'تنظیمات',
                'ordering': ['category', 'key'],
            },
        ),
    ]
