# Generated by Django 6.0.7 on 2026-07-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('in', 'ورود'), ('out', 'خروج'), ('adjust', 'اصلاح'), ('waste', 'ضایعات'), ('return', 'برگشت')], max_length=10, verbose_name='نوع تراکنش')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='مقدار')),
                ('unit_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قیمت هر واحد')),
                ('total_price', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='قیمت کل')),
                ('reference_type', models.CharField(blank=True, default='', max_length=50, verbose_name='نوع مرجع')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه مرجع')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت\u200cها')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تراکنش انبار',
                'verbose_name_plural': 'تراکنش\u200cهای انبار',
                'ordering': ['-transaction_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stock', models.PositiveIntegerField(default=0, verbose_name='موجودی فعلی')),
                ('min_stock', models.PositiveIntegerField(default=0, verbose_name='حداقل موجودی')),
                ('last_production_date', models.DateField(blank=True, null=True, verbose_name='آخرین تاریخ تولید')),
            ],
            options={
                'verbose_name': 'موجودی محصول',
                'verbose_name_plural': 'موجودی محصولات',
            },
        ),
        migrations.CreateModel(
            name='ProductInventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('production', 'تولید'), ('sale', 'فروش'), ('return', 'برگشت'), ('adjust', 'اصلاح'), ('waste', 'ضایعات')], max_length=10, verbose_name='نوع تراکنش')),
                ('quantity', models.IntegerField(verbose_name='مقدار')),
                ('reference_type', models.CharField(blank=True, default='', max_length=50, verbose_name='نوع مرجع')),
                ('reference_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='شناسه مرجع')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'تراکنش موجودی محصول',
                'verbose_name_plural': 'تراکنش\u200cهای موجودی محصولات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='مقدار')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت هر واحد')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت کل')),
                ('supplier', models.CharField(max_length=200, verbose_name='تامین\u200cکننده')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100, verbose_name='شماره فاکتور')),
                ('purchase_date', models.DateField(verbose_name='تاریخ خرید')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رکورد خرید',
                'verbose_name_plural': 'رکوردهای خرید',
                'ordering': ['-purchase_date'],
            },
        ),
        migrations.CreateModel(
            name='ReturnRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='مقدار')),
                ('reason', models.TextField(verbose_name='دلیل')),
                ('source', models.CharField(max_length=200, verbose_name='منبع برگشت')),
                ('return_date', models.DateField(verbose_name='تاریخ برگشت')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رکورد برگشت',
                'verbose_name_plural': 'رکوردهای برگشت',
                'ordering': ['-return_date'],
            },
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15, verbose_name='مقدار')),
                ('reason', models.TextField(verbose_name='دلیل')),
                ('waste_date', models.DateField(verbose_name='تاریخ ضایعات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'رکورد ضایعات',
                'verbose_name_plural': 'رکوردهای ضایعات',
                'ordering': ['-waste_date'],
            },
        ),
    ]
