# Generated by Django 5.2.16 on 2026-07-09 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_initial'),
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventorytransaction',
            name='type',
            field=models.CharField(choices=[('production', 'تولید'), ('sale', 'فروش'), ('purchase', 'خرید'), ('return', 'برگشت'), ('adjust', 'اصلاح'), ('waste', 'ضایعات')], max_length=10, verbose_name='نوع تراکنش'),
        ),
        migrations.CreateModel(
            name='ProductPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='مقدار')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت هر واحد')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت کل')),
                ('supplier', models.CharField(max_length=200, verbose_name='تامین\u200cکننده')),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100, verbose_name='شماره فاکتور')),
                ('purchase_date', models.DateField(verbose_name='تاریخ خرید')),
                ('notes', models.TextField(blank=True, default='', verbose_name='یادداشت\u200cها')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد کننده')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to='products.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'رکورد خرید محصول',
                'verbose_name_plural': 'رکوردهای خرید محصولات',
                'ordering': ['-purchase_date'],
            },
        ),
    ]
