# Generated by Django 5.2.16 on 2026-07-10 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_productinventorytransaction_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinventory',
            name='current_stock',
            field=models.IntegerField(default=0, verbose_name='موجودی فعلی'),
        ),
    ]
