# Generated by Django 5.2.16 on 2026-07-12 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_productinventory_current_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpurchase',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ خرید'),
        ),
        migrations.AlterField(
            model_name='purchaserecord',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ خرید'),
        ),
    ]
