# Generated by Django 6.0.7 on 2026-07-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام')),
                ('phone', models.CharField(blank=True, default='', max_length=15, verbose_name='تلفن')),
                ('role', models.CharField(choices=[('welder', 'جوشکار'), ('assembler', 'مونتاژکار'), ('painter', 'رنگ\u200cکار'), ('packer', 'بسته\u200cبند'), ('operator', 'اپراتور'), ('other', 'سایر')], default='other', max_length=20, verbose_name='نقش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'کارگر',
                'verbose_name_plural': 'کارگران',
                'ordering': ['name'],
            },
        ),
    ]
