# Generated by Django 5.2.16 on 2026-07-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='address',
            field=models.TextField(blank=True, default='', verbose_name='آدرس'),
        ),
        migrations.AddField(
            model_name='worker',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ تولد'),
        ),
        migrations.AddField(
            model_name='worker',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='worker',
            name='emergency_phone',
            field=models.CharField(blank=True, default='', max_length=15, verbose_name='تلفن اضطراری'),
        ),
        migrations.AddField(
            model_name='worker',
            name='experience_years',
            field=models.PositiveIntegerField(default=0, verbose_name='سال\u200cهای تجربه'),
        ),
        migrations.AddField(
            model_name='worker',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاریخ استخدام'),
        ),
        migrations.AddField(
            model_name='worker',
            name='insurance_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='شماره بیمه'),
        ),
        migrations.AddField(
            model_name='worker',
            name='national_id',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='worker',
            name='salary',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='حقوق (ریال)'),
        ),
        migrations.AddField(
            model_name='worker',
            name='skill',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='مهارت اصلی'),
        ),
    ]
