# Generated by Django 6.0.7 on 2026-07-07 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('kavenegar', 'کاوه\u200cنگار'), ('smsir', 'SMS.ir')], max_length=20, unique=True, verbose_name='ارائه\u200cدهنده')),
                ('api_key', models.CharField(max_length=200, verbose_name='کلید API')),
                ('sender_number', models.CharField(max_length=15, verbose_name='شماره فرستنده')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'تنظیمات ارائه\u200cدهنده پیامک',
                'verbose_name_plural': 'تنظیمات ارائه\u200cدهندگان پیامک',
            },
        ),
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('body', models.TextField(verbose_name='متن پیامک')),
                ('category', models.CharField(choices=[('general', 'عمومی'), ('discount', 'تخفیف'), ('new_product', 'محصول جدید'), ('order', 'سفارش'), ('payment', 'پرداخت'), ('holiday', 'تعطیلات'), ('birthday', 'تولد'), ('promotion', 'تبلیغاتی')], default='general', max_length=20, verbose_name='دسته\u200cبندی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'قالب پیامک',
                'verbose_name_plural': 'قالب\u200cهای پیامک',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SMSMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=15, verbose_name='شماره تلفن')),
                ('message', models.TextField(verbose_name='متن پیام')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('sent', 'ارسال شده'), ('failed', 'ناموفق')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('provider', models.CharField(default='demo', max_length=20, verbose_name='ارائه\u200cدهنده')),
                ('provider_message_id', models.CharField(blank=True, default='', max_length=100, verbose_name='شناسه پیام ارائه\u200cدهنده')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='پیام خطا')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer', verbose_name='مشتری')),
            ],
            options={
                'verbose_name': 'پیامک',
                'verbose_name_plural': 'پیامک\u200cها',
                'ordering': ['-sent_at'],
            },
        ),
    ]
