# Generated by Django 6.0.8 on 2026-09-07 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_invoice_deduct_stock'),
        ('sms', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='smsmessage',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.invoice', verbose_name='فاکتور'),
        ),
        migrations.AlterField(
            model_name='smstemplate',
            name='category',
            field=models.CharField(choices=[('general', 'عمومی'), ('discount', 'تخفیف'), ('new_product', 'محصول جدید'), ('order', 'سفارش'), ('payment', 'پرداخت'), ('holiday', 'تعطیلات'), ('birthday', 'تولد'), ('promotion', 'تبلیغاتی'), ('invoice', 'فاکتور')], default='general', max_length=20, verbose_name='دسته\u200cبندی'),
        ),
    ]
