# Generated by Django 5.2.16 on 2026-07-12 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UpdateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_from', models.CharField(max_length=50, verbose_name='ورژن قبلی')),
                ('version_to', models.CharField(max_length=50, verbose_name='ورژن جدید')),
                ('status', models.CharField(choices=[('pending', 'در انتظار'), ('downloading', 'در حال دانلود'), ('updating', 'در حال آپدیت'), ('success', 'موفق'), ('failed', 'ناموفق'), ('rollback', 'بازگشت')], default='pending', max_length=20)),
                ('backup_path', models.CharField(blank=True, max_length=500, verbose_name='مسیر بک\u200cآپ')),
                ('error_message', models.TextField(blank=True, verbose_name='پیام خطا')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان پایان')),
                ('triggered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='توسط کاربر')),
            ],
            options={
                'verbose_name': 'لاگ آپدیت',
                'verbose_name_plural': 'لاگ\u200cهای آپدیت',
                'ordering': ['-started_at'],
            },
        ),
    ]
